services:
  php:
    image: php:8.2-fpm
    volumes:
      - ./www:/var/www/html
    user: "1000:1000"

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php